DROP TABLE CUSTOMER IF EXISTS;

CREATE TABLE CUSTOMER (
	DNI VARCHAR(8) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50),
	BIRTH_DATE DATE,
	CREATE_DATE DATE
);

INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('23150497', 'AMADOR', 'ALANIA', 'aamador@gmail.com', PARSEDATETIME('12/06/1985', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('19979598', 'TIMOTEO', 'ALANYA', 'talanya@gmail.com', PARSEDATETIME('02/08/1985', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('07296320', 'HIPOLITO', 'ALAYO', 'halayo@gmail.com', PARSEDATETIME('01/11/1985', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('21062494', 'JOSE', 'LEYVA', 'jleyva@gmail.com', PARSEDATETIME('01/11/1985', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('07775642', 'GRACIELA', 'AYUQUE', 'gayuque@gmail.com', PARSEDATETIME('01/11/1985', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('23204150', 'MAXIMO', 'ARCE', 'marce@gmail.com', PARSEDATETIME('11/02/1986', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('21104701', 'MARCELO', 'ARIAS', 'marias@gmail.com', PARSEDATETIME('04/02/1986', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('25529875', 'ADAN', 'ARISMENDI', 'aarismendi@gmail.com', PARSEDATETIME('24/03/1986', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('16132432', 'AUDULIO', 'BUSTAMANTE', 'abustamante@gmail.com', PARSEDATETIME('21/01/1987', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('07012945', 'CARLOS', 'SAPAICO', 'csapaico@gmail.com', PARSEDATETIME('12/01/1987', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('19977910', 'VICTOR', 'ARTEAGA', 'varteaga@gmail.com', PARSEDATETIME('04/05/1987', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('31031524', 'CLAUDIO', 'ASCANOA', 'cascanoa@gmail.com', PARSEDATETIME('05/05/1987', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('23655129', 'OSCAR', 'AVELLANEDA', 'oavellaneda@gmail.com', PARSEDATETIME('19/06/1987', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('21808999', 'TEODOSIO', 'GARCIA', 'tgarcia@gmail.com', PARSEDATETIME('02/01/1988', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('09097237', 'ESMELDA', 'ALVAREZ', 'ealvarez@gmail.com', PARSEDATETIME('01/01/1988', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('25545029', 'ISABEL', 'REINOSO', 'ireynoso@gmail.com', PARSEDATETIME('22/02/1988', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('08614939', 'MARCO', 'CUBA', 'mcuba@gmail.com', PARSEDATETIME('20/02/1988', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('25676103', 'ROSALBINA', 'BAILETTI', 'rbailetti@gmail.com', PARSEDATETIME('14/08/1988', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('25521675', 'ANDRES', 'CALLE', 'acalle@gmail.com', PARSEDATETIME('12/08/1988', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('32760792', 'ANGELA', 'LLANOS', 'allanos@gmail.com', PARSEDATETIME('19/09/1988', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('04303213', 'ALEJANDRO', 'ESPINOZA', 'aespinoza@gmail.com', PARSEDATETIME('24/02/1989', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('15391392', 'ISABEL', 'BUSTAMANTE', 'ibustamante@gmail.com', PARSEDATETIME('01/02/1989', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('06544761', 'EUSEBIO', 'CABEZAS', 'ecabezas@gmail.com', PARSEDATETIME('03/03/1989', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('16617381', 'VICTOR', 'CAMPOS', 'vcampos@gmail.com', PARSEDATETIME('10/11/1989', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('23847239', 'SILVINO', 'FERNANDEZ', 'sfernandez@gmail.com', PARSEDATETIME('13/11/1989', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('20010271', 'CELSO', 'CALDERON', 'ccalderon@gmail.com', PARSEDATETIME('10/01/1990', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('20646882', 'CARMELA', 'YACTAYO', 'cyactayo@gmail.com', PARSEDATETIME('02/08/1990', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('19980186', 'JUAN', 'ALVAREZ', 'jalvarez@gmail.com', PARSEDATETIME('11/08/1990', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('19893998', 'ALVARO', 'CANCHARI', 'acanchari@gmail.com', PARSEDATETIME('10/12/1990', 'dd/MM/yyyy'), NOW());
INSERT INTO CUSTOMER (DNI, NAME, LAST_NAME, EMAIL, BIRTH_DATE, CREATE_DATE) VALUES ('07336320', 'ORLANDO', 'AGUILAR', 'oaguilar@gmail.com', PARSEDATETIME('20/12/1990', 'dd/MM/yyyy'), NOW());

COMMIT;